/*****************************************************************************
* Copyright 2010 Nexteer Automotive, All Rights Reserved.
* Nexteer Confidential
*
* Module File Name  : EcuStartup.c
* Module Description: AUTOSAR Startup Sequence
* Product           : Gen II Plus - EA3.0
* Author            : Jeremy Warmbier
*****************************************************************************/
/* Version Control:
 * Date Created:      Wed Apr 13 12:17:00 2011
 * %version:          EA3#9 %
 * %derived_by:       fz9hxm %
 * %date_modified:    Fri Oct 18 11:33:29 2013 %
 *---------------------------------------------------------------------------------------------------------------------
 * Date      Rev      Author         Change Description                                                        SCR #
 * -------   -------  --------  ---------------------------------------------------------------------------  ----------
 * 07/29/13  1        LWW       Initial C1xx Synergy Version
 * 08/14/13  2        LWW       Added call to Nexteer Spi Init
 * 10/16/13  3        BWL       Reduced flash wait states as temporary throughput fix.
 * 10/18/14  4        BWL       Add OS Register write call to flash wait state write.
 * 04/02/14  5        BWL       Replace Metircs with Gliwa T1
 * 04/03/14  6        BWL       Remove flash wait state change in version 3.
 * 04/10/16  9        CP        EA3#4996:Fee resume/suspend fn calls placed around the NvM_ReadAll()         EA3#6847 
 */


/**************************************************************************************************
* Include files
**************************************************************************************************/

/*
 * Description: The V_Cfg header is generated by the generation tool. Important 
 *              information like CPU and compiler type, manufacturer information
 *              and a list of currently used CANbedded modules is defined here.
 */
#include "Std_Types.h"
#include "V_Cfg.h"
#include "EcuStartup.h"
#include "NvM_Cfg.h"
#include "ApplCallbacks.h"
#include "Nhet.h"
#include "Adc2.h"
#include "PwmCdd.h"
#include "Ap_DfltConfigData.h"
#include "Interrupts.h"
#include "desc.h"
#include "SystemTime.h"
#include "FlsTst.h"
#include "T1_AppInterface.h"
#include "Cd_FeeIf.h"


/*****************************************************************************
 * Include the CANbedded files 
 *****************************************************************************/
#if defined( VGEN_ENABLE_SYSSERVICE_ASRDET )
# include "Det.h"
#endif /* VGEN_ENABLE_SYSSERVICE_ASRDET */

#include "ggda.h"
# include "NvM.h"
# include "EcuM.h"
# include "SchM.h"
# include "Dem.h"
# include "MemIf_Types.h"
# include "Adc.h"
# include "Gpt.h"
# include "Mcu.h"
# include "Port.h"
#include "ComM.h"
# include "IoHwAb.h"
# include "XcpProf.h"
# include "CDD_Func.h"
# include "ePWM.h"
#include "Ap_ApXcp.h"
#include "NtWrap.h"
#include "Dma.h"

extern FUNC(void, AUTOMATIC) appdesc_init(void);

/*****************************************************************************
  * Name:        main
  * Description: 
  * Inputs:      None 
  * Outputs:     None
  *
*****************************************************************************/
int main(void) 
{
	T1_AppInit();
	osInitialize();
	EcuM_Init();
}

/*****************************************************************************
  * Name:        EcuStartup_Init1
  * Description: Initialization executed prior to OS start  
  * Inputs:      None 
  * Outputs:     None
  *
*****************************************************************************/
void EcuStartup_Init1(void) 
{
#if defined( VGEN_ENABLE_SYSSERVICE_ASRDET )
  Det_Init();
  Det_Start();  /* must be initialized before other components */
#endif
  VStdInitPowerOn();
  Dem_PreInit();
  
  ComM_InitMemory();
  SchM_InitMemory();
  ApXcp_Init();
  
  Dma_Init();

  /* uDiag Init Functions */
  FlsTst_Init(&FlsTst_Runtime);
  uDiagCCRM_Init();
  uDiagClockMonitor_Init();
  uDiagECC_Init();
  uDiagESM_Init();
  uDiagIOMM_Init();
  uDiagParity_Init();
  uDiagPeriphMPU_Init();
  uDiagStaticRegs_Init();
  uDiagVIM_Init();
  
  Nhet_Init1();
  ePWM_Init1();
  SpiNxt_Init();
  Dma_SetupMtrCtrlGroups();
}

/*****************************************************************************
  * Name:        EcuStartup_Init2
  * Description: Initialization executed after OS start  
  * Inputs:      None 
  * Outputs:     None
  *
*****************************************************************************/
void EcuStartup_Init2(void)
{
  Gpt_Init(&Gpt_Runtime);
  SystemTime_Init();
  NtWrapC_Adc_Init();
  Call_Adc2_Init1();
  Call_PwmCdd_Init();

  EnableCRCInterrupt();
  Port_Init(&Port_Runtime);

  IlInitPowerOn();
  TpInitPowerOn();
  DescInitPowerOn(0);
  GgdaInitPowerOn();

  NvM_Init();
  TWrapC_FeeIf_Init();
  
  TWrapC_TI_Fee_SuspendResumeErase(Suspend_Erase);
  NvM_ReadAll();
  /* TODO:  See if startup can be optimized to minimize NVM waiting */
  Appl_WaitNvMReady(0, TRUE);
  TWrapC_TI_Fee_SuspendResumeErase(Resume_Erase);
  
  DfltConfigData_Init1();
  DemIf_Init();
  Dem_Init();
   /* After the NvM driver has completed initializing the unsecured memory, execute the NvMProxy_Init to
  * transfer the data to secured memory.
  * Execution of the NvMProxy_Init function requires a trusted function call to place the system into a
  * privileged state that allows writing to the secured memory regions.
  *
  * TODO: Ensure the read process for all deprecated block migration is completed prior to invoking.
  */
  Call_NvMProxy_Init();

  EnableOverVoltThreshInterrupt();

  AppDesc_Init();
  

  EnableESMLInterrupt();
  EnableCanInterrupt();
}


