/* file: trustfct.c, automatically generated by genTMS570SafeCtxAS.exe, Version: 5.07 */
/* configuration read from: C:\Users\fz9hxm\AppData\Local\Temp\~cfg4_314_EPS.ecuc.arxml.oil */
/* generation at  : Tue Apr 26 16:04:41 2016 */
/* Unlimited license CBD1010124 for Nexteer Automotive */
/* Implementation: TMS570LS3x */
/* Version of general code: 5.23c */

#if defined USE_QUOTE_INCLUDES
 #include "vrm.h"
#else
 #include <vrm.h>
#endif
#define osdVrmGenMajRelNum 5
#define osdVrmGenMinRelNum 7
#if defined USE_QUOTE_INCLUDES
 #include "vrm.h"
#else
 #include <vrm.h>
#endif

#if defined USE_QUOTE_INCLUDES
 #include "Os.h"
#else
 #include <Os.h>
#endif

#pragma SET_DATA_SECTION(".osconst")

#pragma SET_CODE_SECTION(".oscode")

osqROM0 osqROM1 const osqROM2 TrustedFunctionType osqROM3 oskTrustedFctTab[osdNumberOfTrustedFunctions]=
{
   TRUSTED_NtWrapS_NvMProxy_Init,
   TRUSTED_TWrapS_Appdesc_BLTransition,
   TRUSTED_NtWrapS_PwmCdd_Init,
   TRUSTED_NtWrapS_Adc2_Init1,
   TRUSTED_NtWrapS_Wdg_TMS570LS3x_Init,
   TRUSTED_NtWrapS_WdgM_Init,
   TRUSTED_NtWrapS_Adc_Init,
   TRUSTED_TWrapS_XcpWriteAp0,
   TRUSTED_NtWrapS_ProcessF0FF,
   TRUSTED_NtWrapS_StaMd_Init1,
   TRUSTED_TWrapS_FeeIf_Init,
   TRUSTED_TWrapS_Fee_MainFunction,
   TRUSTED_TWrapS_Fee_Read,
   TRUSTED_TWrapS_Fee_Write,
   TRUSTED_TWrapS_Fee_EraseImmediateBlock,
   TRUSTED_TWrapS_Fee_InvalidateBlock,
   TRUSTED_TWrapS_Fee_Cancel,
   TRUSTED_TWrapS_Fee_GetStatus,
   TRUSTED_TWrapS_Fee_GetJobResult,
   TRUSTED_TWrapS_uDiagVIM_RednRpdShtdn,
   TRUSTED_TWrapS_uDiagECC_RednRpdShtdn,
   TRUSTED_TWrapS_Dma_InvalidateSlowADCGroup,
   TRUSTED_TWrapS_TI_Fee_SuspendResumeErase,
};

#ifndef OS_SUPPRESS_CALLEESTUB
#endif /* OS_SUPPRESS_CALLEESTUB */
osqROM0 osqROM1 const osqROM2 NonTrustedFunctionType osqROM3 oskNonTrustedFctTab[osdNumberOfNonTrustedFunctions]=
{
   NONTRUSTED_NtWrapS_AssistLmtFunc_Scom_ManualTrqCmd,
   NONTRUSTED_NtWrapS_SCom_EOLNomMtrParam_Set,
   NONTRUSTED_NtWrapS_TrqCmdScl_SCom_Set,
   NONTRUSTED_NtWrapS_Polarity_SCom_SetPolarity,
   NONTRUSTED_NtWrapS_CmMtrCurr_SCom_CalGain,
   NONTRUSTED_NtWrapS_CmMtrCurr_SCom_CalOffset,
   NONTRUSTED_NtWrapS_CmMtrCurr_SCom_SetMtrCurrCals,
   NONTRUSTED_NtWrapS_XcpWriteAp10,
   NONTRUSTED_NtWrapS_TrqCanc_Scom_SetCogTrqCal,
   NONTRUSTED_NtWrapS_DigHwTrqSENT_SCom_ClrTrqTrim,
   NONTRUSTED_NtWrapS_DigHwTrqSENT_SCom_SetTrqTrim,
   NONTRUSTED_NtWrapS_DigHwTrqSENT_SCom_WriteData,
   NONTRUSTED_NtWrapS_DigColPs_SCom_CustSetTrim,
   NONTRUSTED_NtWrapS_DigColPs_SCom_CustClearTrim,
   NONTRUSTED_NtWrapS_DigColPs_SCom_NxtSetTrim,
   NONTRUSTED_NtWrapS_DigColPs_SCom_NxtClearTrim,
   NONTRUSTED_NtWrapS_GenPosTraj_SCom_SetInputParam,
   NONTRUSTED_NtWrapS_TSMit_SCom_GainReset,
   NONTRUSTED_NtWrapS_VehDyn_SCom_ForceCenter,
   NONTRUSTED_NtWrapS_XcpWriteAp8,
   NONTRUSTED_NtWrapS_XcpWriteAp9,
};

osqROM0 osqROM1 const osqROM2 ApplicationType osqROM3 oskNTFToAppl[osdNumberOfNonTrustedFunctions]=
{
   Ap_10,
   Ap_10,
   Ap_10,
   Ap_10,
   Ap_10,
   Ap_10,
   Ap_10,
   Ap_10,
   Ap_10,
   Ap_10,
   Ap_10,
   Ap_10,
   Ap_10,
   Ap_10,
   Ap_10,
   Ap_10,
   Ap_10,
   Ap_10,
   Ap_10,
   Ap_8,
   Ap_9,
};

#pragma SET_DATA_SECTION()

#pragma SET_CODE_SECTION()


/* END OF C:\02_EA3Int\C1xx\Wip_fz9hxm\GM_C1XX_EPS_TMS570\Tools\AsrProject\..\..\SwProject\Source\GenData\\..\GenDataOs\trustfct.c */

