/* -----------------------------------------------------------------------------
  Filename:    appdesc.h
  Description: Interface towards the application used by CANdesc.
                
                Manufacturer: General Motors
                EcuDocFile:   C:\02_EA3Int\C1xx\Wip_fz9hxm\GM_C1XX_EPS_TMS570\Tools\AsrProject\GENy\EPS_5.0.3_HS_60.cdd
                Variant:      CommonDiagnostics

  Generated by CANdelaGen, Wed May 04 18:35:00 2016
 
 ----------------------------------------------------------------------------- */
/* -----------------------------------------------------------------------------
  C O P Y R I G H T
 -------------------------------------------------------------------------------
  Copyright (c) 2001-2010 by Vector Informatik GmbH. All rights reserved.
 
  This software is copyright protected and proprietary to Vector Informatik 
  GmbH.
  
  Vector Informatik GmbH grants to you only those rights as set out in the 
  license conditions.
  
  All other rights remain with Vector Informatik GmbH.
 -------------------------------------------------------------------------------
 ----------------------------------------------------------------------------- */

#if !defined(__APPDESC_H__)
#define __APPDESC_H__

/* -----------------------------------------------------------------------------
    &&&~ Configuration switches
 ----------------------------------------------------------------------------- */

#if !defined(__DESC_H__)
# error "Include sequence error! You must include desc.h before appDesc.h."
#endif



/* -----------------------------------------------------------------------------
    &&&~ Preprocessor constants (defines)
 ----------------------------------------------------------------------------- */

/* This magic number provides inter CANdesc generation process consistency check.All CANdesc files must have the same one. */
#define DESC_APPLICATION_INTERFACE_MAGIC_NUMBER                      25472


/* -----------------------------------------------------------------------------
    &&&~ Function prototypes
 ----------------------------------------------------------------------------- */

#if defined (DESC_ENABLE_DEBUG_USER ) || defined (DESC_ENABLE_DEBUG_INTERNAL)
/* Assertion function for better integration support. */
void DESC_API_CALLBACK_TYPE ApplDescFatalError(vuint8 errorCode, vuint16 lineNumber);
#endif

void DESC_API_CALLBACK_TYPE ApplDescOnTransitionSecurity_Access(DescStateGroup newState, DescStateGroup formerState);
void DESC_API_CALLBACK_TYPE ApplDescOnTransitionDiagnostic_Mode(DescStateGroup newState, DescStateGroup formerState);
void DESC_API_CALLBACK_TYPE ApplDescOnTransitionDevice_Control(DescStateGroup newState, DescStateGroup formerState);
void DESC_API_CALLBACK_TYPE ApplDescOnTransitionMEC(DescStateGroup newState, DescStateGroup formerState);
/* Diagnostic application state management */
void ApplDescOnDiagActive(void);
void ApplDescOnDiagInactive(void);

#if defined (DESC_ENABLE_SERVICE_10_02)
void ApplDescOnDisableAllDtc(void);
#endif
#if defined (DESC_ENABLE_SERVICE_10_03)
void ApplDescOnEnableDtcChangeDuringDevCtrl(void);
#endif
void ApplDescOnReturnToNormalMode(void);
void ApplDescOnDisableNormalComm(void);
#if defined (DESC_ENABLE_PROGRAMMING_SESSION)
void ApplDescForceEcuReset(void);
#endif
void ApplDescOnEnableNormalComm(void);

/* Whithin this function will be checked if the SId is one of the user specific ones. */
vuint8 DESC_API_CALLBACK_TYPE ApplDescCheckUserService(DescMsgItem sid);
void DESC_API_CALLBACK_TYPE ApplDescClearDiagnosticTroubleCodes(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescStartDisableAllDTCs(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescStartEnableDTCsDuringDeviceControl(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescStartStart_Nexteer_Mode(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescReadByPIDFailure_Record_Data_Identifiers(DescMsgContext* pMsgContext);
/* Request length check can not be performed. Please, implement length check in your Main-Handler!! */
void DESC_API_CALLBACK_TYPE ApplDescRFRD_RFRP(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescRead_DID_02_Calibration_Programmed_Status(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescRead_DID_90_Vehicle_Identification_Number(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescRead_DID_97_System_Name_Or_Engine_Type(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescRead_DID_98_Repair_Shop_Code_Or_Tester_Serial_Number(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescRead_DID_99_Programming_Date(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescRead_DID_9F_Previous_Stored_Repair_Shop_Code_Or_Tester_Serial_Number(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescRead_DID_A0_Manufacturers_Enable_Counter(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescRead_DID_A1_ECU_Configuration_or_Customization_Data_1(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescRead_DID_AB_Compressed_Vehicle_Partitioning_and_Product_Structure_CVPPS(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescRead_DID_B0_ECU_Diagnostic_Address(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescRead_DID_B3_Data_Universal_Numbering_System_Identification_DUNS(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescRead_DID_B4_Manufacturing_Traceability_Characters_new(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescRead_DID_C0_Boot_Software_Part_Number(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescRead_DID_C1_Software_Module_Identifier_1(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescRead_DID_C2_Software_Module_Identifier_2(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescRead_DID_C3_Software_Module_Identifier_3(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescRead_DID_CB_End_Model_Part_Number(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescRead_DID_CC_Base_Model_Part_Number(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescRead_DID_D0_Boot_Software_Part_Number_Alpha_Code(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescRead_DID_D1_Software_Module_Identifier_Alpha_Code_1(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescRead_DID_D2_Software_Module_Identifier_Alpha_Code_2(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescRead_DID_D3_Software_Module_Identifier_Alpha_Code_3(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescRead_DID_DB_End_Model_Part_Number_Alpha_Code(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescRead_DID_DC_Base_Model_Part_Number_Alpha_Code(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescRead_DID_DE_GMLAN_Identification_Data(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescRead_DID_F0_ProgrammedStateIndicator_PSI(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescRead_DID_F3_ECU_ID_ECUI(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescRead_DID_F4_Signature_Bypass_Authorization_Ticket_SBAT(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescRead_DID_F5_DVT_Access_Key_Table_Index_Change_KTIC(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescRead_DID_F6_Boot_Info_Block_Subject_Name_and_ECU_Name(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescReadMemory(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescRequestSPS_Seed(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescSendSPS_Key(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescRequestDevice_Control_Seed(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescSendDevice_Control_Key(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescRequestNexteer_Seed(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescSendNexteer_Key(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescRequestDownloadDownload(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescWrite_DID_02_Calibration_Programmed_Status(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescWrite_DID_90_Vehicle_Identification_Number(DescMsgContext* pMsgContext);
/* Request length check can not be performed. Please, implement length check in your Main-Handler!! */
void DESC_API_CALLBACK_TYPE ApplDescWrite_DID_97_System_Name_Or_Engine_Type(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescWrite_DID_98_Repair_Shop_Code_Or_Tester_Serial_Number(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescWrite_DID_99_Programming_Date(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescWrite_DID_9A_Diagnostic_Data_Identifier(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescWrite_DID_A0_Manufacturers_Enable_Counter(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescWrite_DID_B4_Manufacturing_Traceability_Characters_new(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescWrite_DID_CB_End_Model_Part_Number(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescWrite_DID_DB_End_Model_Part_Number_Alpha_Code(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescWrite_DID_F4_Signature_Bypass_Authorization_Ticket_SBAT(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescWrite_DID_F5_DVT_Access_Key_Table_Index_Change_KTIC(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescReportProgrammingStateProgrammingState(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescControlCPID_0xAE00_Cancel_All_Active_Device_Controls(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescControlCPID_0xAE02_Steering_Assist_Control(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescControlCPID_0xAE03_Steering_Angle_Sensor_Calibration(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescControlCPID_0xAE04_Reset_Adaptive_Data(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescControlCPID_0xAEFD_System_Basic_Functions(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescUserServiceHandler(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescPreDisableNormalCommunication(vuint8 iContext);
void DESC_API_CALLBACK_TYPE ApplDescPreSendTesterPresent(vuint8 iContext);
void DESC_API_CALLBACK_TYPE ApplDescPostControlCPID_0xAE02_Steering_Assist_Control(vuint8 iContext, vuint8 status);
void DESC_API_CALLBACK_TYPE ApplDescPostControlCPID_0xAE03_Steering_Angle_Sensor_Calibration(vuint8 iContext, vuint8 status);
void DESC_API_CALLBACK_TYPE ApplDescPostControlCPID_0xAE04_Reset_Adaptive_Data(vuint8 iContext, vuint8 status);
void DESC_API_CALLBACK_TYPE ApplDescPostControlCPID_0xAEFD_System_Basic_Functions(vuint8 iContext, vuint8 status);
void DESC_API_CALLBACK_TYPE ApplDescPostUserServiceHandler(vuint8 iContext, vuint8 status);
void DESC_API_CALLBACK_TYPE ApplDescReadPackVehicle_System_Status(DescMsg pMsg);
vuint8 DESC_API_CALLBACK_TYPE ApplDescReadDATA_DID_9A_Diagnostic_Data_Identifier(void);
vuint8 DESC_API_CALLBACK_TYPE ApplDescReadVersion_Code_DID_9A_Diagnostic_Data_Identifier(void);
/* Programming mode prechecks */
#if defined (DESC_ENABLE_REQ_HISPEED_PROG)
vuint8 ApplDescMayEnterHiSpeedProgMode(void);
#endif
#if defined (DESC_ENABLE_PROGRAMMING_SESSION)
/* Request programming mode */
vuint8 ApplDescMayEnterProgMode(void);
# if defined (DESC_ENABLE_FLASHABLE_ECU)
/* ---- $A5 sub function $03 ---- */
void   ApplDescOnEnterProgMode(void);
# endif
#endif

/* $81 */
void ApplDescGetDtcStatusByMask(vuint16 iterPos, vuint8 statusMask);

void DESC_API_CALLBACK_TYPE ApplDescRead_Parameter_IdentifierGM_0x4016_Ignition_Cycle_Counter(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescRead_Parameter_IdentifierGM_0x401B_ECU_Internal_Temperature(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescRead_Parameter_IdentifierGM_0x4074_Steering_Wheel_Angle(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescRead_Parameter_IdentifierGM_0x40AC_Steering_Input_Torque(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescRead_Parameter_IdentifierGM_0x40AD_EPS_Motor_Overload_Protection_Incidents(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescRead_Parameter_IdentifierGM_0x40AE_Calculated_System_Temperature(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescRead_Parameter_IdentifierGM_0x40BC_Engine_Speed(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescRead_Parameter_IdentifierGM_0x40BD_Vehicle_Speed_Low_Resolution(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescRead_Parameter_IdentifierGM_0x41D1_Advanced_Park_Assist_Mode_Status(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescRead_Parameter_IdentifierGM_0x41D2_Driver_Mode_Control_State(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescRead_Parameter_IdentifierGM_0x41D3_Electric_Power_Steering_Motor_Current_Commanded(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescRead_Parameter_IdentifierGM_0x41D4_Electric_Power_Steering_Motor_Current_Feedback(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescRead_Parameter_IdentifierGM_0x41D5_Electric_Power_Steering_Torque_Overlay_Status(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescRead_Parameter_IdentifierGM_0x41D6_Electric_Power_Steering_Angle_Overlay_Status(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescRead_Parameter_IdentifierGM_0x41D7_Electric_Power_Steering_Torque_Overlay_Requested(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescRead_Parameter_IdentifierGM_0x41D9_Steering_Output_Torque(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescRead_Parameter_IdentifierGM_0x43AD_Mechanical_Steering_Stops_Position_Learn_Status(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescRead_Parameter_IdentifierGM_0x43D0_Electric_Power_Steering_Stop_Start_Status(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescRead_Parameter_IdentifierGM_0x446F_Electric_Power_Steering_APA_Angle_Overlay_Requested(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescRead_Parameter_IdentifierGM_0x44E4_Calculated_Rack_Travel(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescRead_Parameter_IdentifierGM_0x8002_System_Power_Mode(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescRead_Parameter_IdentifierGM_0x8078_Battery_Voltage_ECU_Monitored(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescRead_Parameter_IdentifierGM_0x819D_Vehicle_Speed_Medium_Resolution(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescRead_Parameter_IdentifierGM_0x82C1_Engine_Running_Status(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescRead_Parameter_IdentifierGM_0xC000_Supplier_Internal_DTC_and_Failure_Type(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescRead_Parameter_IdentifierGM_0xC010_Steering_Angle_Sensor_Status(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescRead_Parameter_IdentifierGM_0xC050_Time_Since_Ignition_On(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescRead_Parameter_IdentifierGM_0xC0AF_EPS_System_Status(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescRead_Parameter_IdentifierNexteer_0xFD01_Internal_Software_Identifier(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescRead_Parameter_IdentifierNexteer_0xFD02_Serial_Comm_Service_Active(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescRead_Parameter_IdentifierNexteer_0xFD07_End_of_Line_Polarity(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescRead_Parameter_IdentifierNexteer_0xFD0B_Wheel_Imbalance_Rejection_Selection(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescRead_Parameter_IdentifierNexteer_0xFD0E_Motor_Stiffness_Check(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescRead_Parameter_IdentifierNexteer_0xFD10_CCP_XCP_Transmit_and_Receive_IDs(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescRead_Parameter_IdentifierNexteer_0xFD12_Current_Mode_Offset_and_Gain(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescRead_Parameter_IdentifierNexteer_0xFD13_Nexteer_Diagnostic_Trouble_Codes(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescRead_Parameter_IdentifierNexteer_0xFD17_Flash_Memory_Size_Read(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescRead_Parameter_IdentifierNexteer_0xFD19_Nexteer_Manufacturing_Enable_Counter(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescRead_Parameter_IdentifierNexteer_0xFD1A_System_State(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescRead_Parameter_IdentifierNexteer_0xFD1B_Manual_Vehicle_Speed_Override(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescRead_Parameter_IdentifierNexteer_0xFD1C_Manufacturing_Services_Version(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescRead_Parameter_IdentifierNexteer_0xFD1E_Manufacturing_Diagnostic_Defeat(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescRead_Parameter_IdentifierNexteer_0xFD20_Transient_Overvoltage_Data(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescRead_Parameter_IdentifierNexteer_0xFD25_Motor_Torque_Scale_Factor(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescRead_Parameter_IdentifierNexteer_0xFD26_Average_Friction_Learning_Select(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescRead_Parameter_IdentifierNexteer_0xFD27_Average_Friction_Offset_Output_Defeat(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescRead_Parameter_IdentifierNexteer_0xFD29_Set_EOL_Friction_Learned(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescRead_Parameter_IdentifierNexteer_0xFD30_EOL_Torque_Trim_Digital_SENT(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescRead_Parameter_IdentifierNexteer_0xFD31_Torque_Sensor_Value_Digital_SENT(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescRead_Parameter_IdentifierNexteer_0xFDA1_ECU_Serial_Number(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescRead_Parameter_IdentifierNexteer_0xFDA2_EPS_Serial_Number(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescRead_Parameter_IdentifierNexteer_0xFDA3_ECU_Hardware_Part_Number(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescRead_Parameter_IdentifierNexteer_0xFDAC_Manufacturing_Scratchpad(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescRead_Parameter_IdentifierNexteer_0xFDAD_Active_Pull_Compensation(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescRead_Parameter_IdentifierNexteer_0xFDAE_Ignition_Counter(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescRead_Parameter_IdentifierNexteer_0xFDAF_Fault_Information_Black_Box(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescRead_Parameter_IdentifierNexteer_0xFDB0_IPM_Cogging_Tbl_1(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescRead_Parameter_IdentifierNexteer_0xFDB1_IPM_Cogging_Tbl_2(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescRead_Parameter_IdentifierNexteer_0xFDB2_IPM_Cogging_Tbl_3(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescRead_Parameter_IdentifierNexteer_0xFDB3_IPM_Cogging_Tbl_4(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescRead_Parameter_IdentifierNexteer_0xFDB4_Current_Mode_Analog_Ke_R_Ld_and_Lq(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescRead_Parameter_IdentifierNexteer_0xFDB5_Active_Pull_Short_Term_Value(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescRead_Parameter_IdentifierNexteer_0xFDB6_Active_Pull_Long_Term_Value(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescRead_Parameter_IdentifierNexteer_0xFDB7_IPM_Cogging_Tbl_5(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescRead_Parameter_IdentifierNexteer_0xFEE0_System_Name_or_Engine_Type(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescRead_Parameter_IdentifierNexteer_0xFEE1_Diagnostic_Data_Identifier(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescRead_Parameter_IdentifierNexteer_0xFEE2_Manufacturing_Traceability_PCB_Manufacturing(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescRead_Parameter_IdentifierNexteer_0xFEE5_Read_Sensor_Torque_EEPROM(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescRead_Parameter_IdentifierNexteer_0xFEE6_End_Model_Part_Number(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescRead_Parameter_IdentifierNexteer_0xFEE7_End_Model_Part_Number_Alpha_Code(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescRead_Parameter_IdentifierNexteer_0xFEE8_Manufacturing_Traceability_Nexteer_Plant(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescRead_Parameter_IdentifierNexteer_0xFEEA_GM_Manufacturing_Enabale_Counter_MEC(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescRead_Parameter_IdentifierNexteer_0xFEEB_Programming_Data(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescRead_Parameter_IdentifierNexteer_0xFEEC_Repair_Shop_Code(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescRead_Parameter_IdentifierNexteer_0xFEED_VIN_Data(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescRead_Parameter_IdentifierNexteer_0xFEEF_WIR_Fault_Status_Information(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescRead_Parameter_IdentifierNexteer_0xFEF1_Data_Universal_Numbering_System_DUNS(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescRead_Parameter_IdentifierNexteer_0xFEF3_Base_Model_Part_Number(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescRead_Parameter_IdentifierNexteer_0xFEF4_Base_Model_Part_Number_Alpha_Code(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescRead_Parameter_IdentifierNexteer_0xFEF5_ECU_ID(DescMsgContext* pMsgContext);
#if defined (DESC_ENABLE_MULTI_CFG_SUPPORT)
/* Additionaly reject a supported PID (multi ECU configuration) */
DescBool ApplDescIsDataIdSupported(vuint16 pid);
#endif



#endif /* __APPDESC_H__ */
