/* -----------------------------------------------------------------------------
  Filename:    Dem_IntErrId.h
  Description: Toolversion: 12.00.01.01.11.00.60.01.00.00
               
               Serial Number: CBD1110060
               Customer Info: Nexteer GM MSR_SLP3_BSW_RTE_wGMLAN TexasInstruments TMS570 Texas Instruments tbd
               
               
               Generator Fwk   : GENy 
               Generator Module: Dem
               
               Configuration   : C:\02_EA3Int\C1xx\Work_Int\GM_C1XX_EPS_TMS570\Tools\AsrProject\Config\DEM\gmHS_AFS_HS.ecuc.vdsxml
               
               ECU: 
                       TargetSystem: Hw_Tms470/570Cpu (Dcan)
                       Compiler:     TexasInstruments
                       Derivates:    TMS570PSFC66
               
               Channel "CAN00":
                       Databasefile: 
                       Bussystem:    CAN
                       Manufacturer: Vector
                       Node:         CanStateManagerConfiguration

  Generated by , 2016-04-10  10:03:49
 ----------------------------------------------------------------------------- */
/* -----------------------------------------------------------------------------
  C O P Y R I G H T
 -------------------------------------------------------------------------------
  Copyright (c) 2001-2011 by Vector Informatik GmbH. All rights reserved.
 
  This software is copyright protected and proprietary to Vector Informatik 
  GmbH.
  
  Vector Informatik GmbH grants to you only those rights as set out in the 
  license conditions.
  
  All other rights remain with Vector Informatik GmbH.
 -------------------------------------------------------------------------------
 ----------------------------------------------------------------------------- */

#if !defined(DEM_INTERRID_H)
#define DEM_INTERRID_H

/* -----------------------------------------------------------------------------
    &&&~ 
 ----------------------------------------------------------------------------- */

#define Dem_CANTRCV_E_NO_TRCV_CONTROL        27
#define Dem_PDUR_E_PDU_INSTANCE_LOST         28
#define Dem_PDUR_E_INIT_FAILED               29
#define Dem_COMM_E_NET_START_IND_CHANNEL_0   30
#define Dem_CAN_E_TIMEOUT                    31
#define Dem_CANIF_E_INVALID_DLC              32
#define Dem_CANSM_E_MODE_CHANGE_NETWORK_0    33
#define Dem_CANSM_E_MODE_CHANGE_NETWORK_1    34
#define Dem_CANSM_E_BUSOFF_NETWORK_0         35
#define Dem_CANSM_E_BUSOFF_NETWORK_1         36
#define Dem_CANSM_E_SETTRANSCEIVERMODE_NETWORK_0 37
#define Dem_CANSM_E_SETTRANSCEIVERMODE_NETWORK_1 38
#define Dem_LINSM_E_CONFIRMATION_TIMEOUT     39
#define Dem_COMM_E_NET_START_IND_CHANNEL_1   40
#define Dem_COMM_E_NET_START_IND_CHANNEL_2   41
#define Dem_ECUM_E_ALL_RUN_REQUESTS_KILLED   42
#define Dem_ECUM_E_RAM_CHECKED_FAILED        43
#define Dem_NVM_E_REQ_FAILED                 44
#define Dem_NVM_E_INTEGRITY_FAILED           45
#define Dem_FLS_E_ERASE_FAILED               46
#define Dem_FLS_E_WRITE_FAILED               47
#define Dem_FLS_E_READ_FAILED                48
#define Dem_FLS_E_COMPARE_FAILED             49
#define Dem_FRIF_E_JLE_SYNC                  50
#define Dem_FRNM_E_INIT_FAILED               51
#define Dem_FRSM_E_CLUSTER_STARTUP           52
#define Dem_FRTRCV_E_FR_NO_TRCV_CONTROL      53
#define Dem_WDGM_E_SET_MODE                  54
#define Dem_WDGM_E_ALIVE_SUPERVISION         55


/* begin Fileversion check */
#ifndef SKIP_MAGIC_NUMBER
#ifdef MAGIC_NUMBER
  #if MAGIC_NUMBER != 219868741
      #error "The magic number of the generated file <C:\02_EA3Int\C1xx\Work_Int\GM_C1XX_EPS_TMS570\SwProject\Source\_GenData\Dem_IntErrId.h> is different. Please check time and date of generated files!"
  #endif
#else
  #define MAGIC_NUMBER 219868741
#endif  /* MAGIC_NUMBER */
#endif  /* SKIP_MAGIC_NUMBER */

/* end Fileversion check */

#endif /* DEM_INTERRID_H */
