/* -----------------------------------------------------------------------------
  Filename:    Dem_IntEvtId.h
  Description: Toolversion: 12.00.01.01.11.00.60.01.00.00
               
               Serial Number: CBD1110060
               Customer Info: Nexteer GM MSR_SLP3_BSW_RTE_wGMLAN TexasInstruments TMS570 Texas Instruments tbd
               
               
               Generator Fwk   : GENy 
               Generator Module: Dem
               
               Configuration   : C:\02_EA3Int\C1xx\Work_Int\GM_C1XX_EPS_TMS570\Tools\AsrProject\Config\DEM\gmHS_AFS_HS.ecuc.vdsxml
               
               ECU: 
                       TargetSystem: Hw_Tms470/570Cpu (Dcan)
                       Compiler:     TexasInstruments
                       Derivates:    TMS570PSFC66
               
               Channel "CAN00":
                       Databasefile: 
                       Bussystem:    CAN
                       Manufacturer: Vector
                       Node:         CanStateManagerConfiguration

  Generated by , 2016-04-10  10:03:49
 ----------------------------------------------------------------------------- */
/* -----------------------------------------------------------------------------
  C O P Y R I G H T
 -------------------------------------------------------------------------------
  Copyright (c) 2001-2011 by Vector Informatik GmbH. All rights reserved.
 
  This software is copyright protected and proprietary to Vector Informatik 
  GmbH.
  
  Vector Informatik GmbH grants to you only those rights as set out in the 
  license conditions.
  
  All other rights remain with Vector Informatik GmbH.
 -------------------------------------------------------------------------------
 ----------------------------------------------------------------------------- */

#if !defined(DEM_INTEVTID_H)
#define DEM_INTEVTID_H

/* -----------------------------------------------------------------------------
    &&&~ 
 ----------------------------------------------------------------------------- */

#define DEM_EVENT_INVALID                    0
#define Dem_EBCM_INVALID_DATA_CE             1
#define Dem_EBCM_LOST_COM_CE                 2
#define Dem_FCM_INVALID_DATA                 3
#define Dem_PACM_INVALID_DATA                4
#define Dem_BCM_INVALID_DATA                 5
#define Dem_EBCM_INVALID_DATA                6
#define Dem_TCM_INVALID_DATA                 7
#define Dem_ECM_INVALID_DATA_HS              8
#define Dem_FCM_LOST_COM                     9
#define Dem_PACM_LOST_COM                    10
#define Dem_BCM_LOST_COMM                    11
#define Dem_EBCM_LOST_COM                    12
#define Dem_TCM_LOST_COMM                    13
#define Dem_ECM_LOST_COMM_ENG_ON             14
#define Dem_BUS_OFF_CE                       15
#define Dem_BUS_OFF_HS                       16
#define Dem_LOW_VOLTAGE                      17
#define Dem_HIGH_VOLTAGE                     18
#define Dem_VOLTAGE_BELOW_THRES              19
#define Dem_SW_PERF_CAL_NOT_PROG             20
#define Dem_ECU_HW_PERFORMANCE               21
#define Dem_STEER_WHEEL_TRQ_INP_SENSOR       22
#define Dem_SWA_PLAUSIBILITY                 23
#define Dem_SWA_HW_FAULT                     24
#define Dem_SWA_CAL_NOT_LEARNED              25
#define Dem_TEMPERATURE_TOO_HIGH             26


/* begin Fileversion check */
#ifndef SKIP_MAGIC_NUMBER
#ifdef MAGIC_NUMBER
  #if MAGIC_NUMBER != 219868741
      #error "The magic number of the generated file <C:\02_EA3Int\C1xx\Work_Int\GM_C1XX_EPS_TMS570\SwProject\Source\_GenData\Dem_IntEvtId.h> is different. Please check time and date of generated files!"
  #endif
#else
  #define MAGIC_NUMBER 219868741
#endif  /* MAGIC_NUMBER */
#endif  /* SKIP_MAGIC_NUMBER */

/* end Fileversion check */

#endif /* DEM_INTEVTID_H */
