/* -----------------------------------------------------------------------------
  Filename:    v_par_1.h
  Description: Toolversion: 12.00.01.01.11.00.60.01.00.00
               
               Serial Number: CBD1110060
               Customer Info: Nexteer GM MSR_SLP3_BSW_RTE_wGMLAN TexasInstruments TMS570 Texas Instruments tbd
               
               
               Generator Fwk   : GENy 
               Generator Module: GenTool_GenyVcfgNameDecorator
               
               Configuration   : C:\02_EA3Int\C1xx\Work_Int\GM_C1XX_EPS_TMS570\Tools\AsrProject\Config\DEM\gmHS_AFS_HS.ecuc.vdsxml
               
               ECU: 
                       TargetSystem: Hw_Tms470/570Cpu (Dcan)
                       Compiler:     TexasInstruments
                       Derivates:    TMS570PSFC66
               
               Channel "CAN00":
                       Databasefile: 
                       Bussystem:    CAN
                       Manufacturer: Vector
                       Node:         CanStateManagerConfiguration

  Generated by , 2016-04-10  10:03:49
 ----------------------------------------------------------------------------- */
/* -----------------------------------------------------------------------------
  C O P Y R I G H T
 -------------------------------------------------------------------------------
  Copyright (c) 2001-2011 by Vector Informatik GmbH. All rights reserved.
 
  This software is copyright protected and proprietary to Vector Informatik 
  GmbH.
  
  Vector Informatik GmbH grants to you only those rights as set out in the 
  license conditions.
  
  All other rights remain with Vector Informatik GmbH.
 -------------------------------------------------------------------------------
 ----------------------------------------------------------------------------- */

#if !defined(__V_PAR_1_H__)
#define __V_PAR_1_H__

/* -----------------------------------------------------------------------------
    &&&~ BaseEnv_PHF_Includes
 ----------------------------------------------------------------------------- */

#include "v_cfg.h"
#include "v_def.h"


/* -----------------------------------------------------------------------------
    &&&~ GENy Version Information
 ----------------------------------------------------------------------------- */

#define VGEN_DELIVERY_VERSION_BYTE_0_1       0x12
#define VGEN_DELIVERY_VERSION_BYTE_1_1       0x00
#define VGEN_DELIVERY_VERSION_BYTE_2_1       0x01
#define VGEN_DELIVERY_VERSION_BYTE_3_1       0x01
#define VGEN_DELIVERY_VERSION_BYTE_4_1       0x11
#define VGEN_DELIVERY_VERSION_BYTE_5_1       0x00
#define VGEN_DELIVERY_VERSION_BYTE_6_1       0x60
#define VGEN_DELIVERY_VERSION_BYTE_7_1       0x01
#define VGEN_DELIVERY_VERSION_BYTE_8_1       0x00
#define VGEN_DELIVERY_VERSION_BYTE_9_1       0x00
#define kGENyVersionNumberOfBytes_1          10
/* ROM CATEGORY 4 START */
V_MEMROM0 extern  V_MEMROM1 vuint8 V_MEMROM2 kGENyVersion_1[kGENyVersionNumberOfBytes_1];
/* ROM CATEGORY 4 END */




/* begin Fileversion check */
#ifndef SKIP_MAGIC_NUMBER
#ifdef MAGIC_NUMBER
  #if MAGIC_NUMBER != 219868741
      #error "The magic number of the generated file <C:\02_EA3Int\C1xx\Work_Int\GM_C1XX_EPS_TMS570\SwProject\Source\_GenData\v_par_1.h> is different. Please check time and date of generated files!"
  #endif
#else
  #define MAGIC_NUMBER 219868741
#endif  /* MAGIC_NUMBER */
#endif  /* SKIP_MAGIC_NUMBER */

/* end Fileversion check */

#endif /* __V_PAR_1_H__ */
