/* -----------------------------------------------------------------------------
  Filename:    can_par.h
  Description: Toolversion: 08.31.00.01.01.01.23.01.00.00
                
                Serial Number: CBD1010123
                Customer Info: Nexteer
                               Package: GM GMLAN_30_Indx 
                               Micro: TI TMS570 TMS570X5LS20216
                               Compiler: Code Composer Studio 4.6.4
                
                
                Generator Fwk   : GENy 
                Generator Module: DrvCan__base
                
                Configuration   : C:\_synergy\9BXX_CZ8L9T\GM_9BXX_EPS_TMS570\Tools\AsrProject\GENy\RT_2.0_Mod.gny
                
                ECU: 
                        TargetSystem: Hw_Tms470/570Cpu (Dcan)
                        Compiler:     TexasInstruments
                        Derivates:    TMS570PSFC66
                
                Channel "Channel0":
                        Databasefile: C:\_synergy\9BXX_CZ8L9T\GM_9BXX_EPS_TMS570\Tools\AsrProject\GENy\GlobalA_HS.dbc
                        Bussystem:    CAN
                        Manufacturer: General Motors
                        Node:         EPS_HS
                Channel "Channel1":
                        Databasefile: C:\Synergy\GM_C1XX_EPS_TMS570-zz4r1x1\GM_C1XX_EPS_TMS570\Tools\AsrProject\GENy\GlobalA_CE.dbc
                        Bussystem:    CAN
                        Manufacturer: General Motors
                        Node:         EPS_CE

  Generated by , 2016-04-28  10:27:04
 ----------------------------------------------------------------------------- */
/* -----------------------------------------------------------------------------
  C O P Y R I G H T
 -------------------------------------------------------------------------------
  Copyright (c) 2001-2008 by Vector Informatik GmbH. All rights reserved.
 
  This software is copyright protected and proprietary to Vector Informatik 
  GmbH.
  
  Vector Informatik GmbH grants to you only those rights as set out in the 
  license conditions.
  
  All other rights remain with Vector Informatik GmbH.
 -------------------------------------------------------------------------------
 ----------------------------------------------------------------------------- */

#if !defined(__CAN_PAR_H__)
#define __CAN_PAR_H__

#include "can_cfg.h"

typedef vuint16           CanChannelHandle;
typedef vuint16           CanTransmitHandle;
#define NM_CHANNEL_APPLTYPE_ONLY              CanChannelHandle channel

extern void Appl_1E5MsgTxAck_HS(CanTransmitHandle txObject);
extern void Appl_1E5MsgTxAck_CE(CanTransmitHandle txObject);
extern void ApplNwmBusoff( NM_CHANNEL_APPLTYPE_ONLY );
extern void ApplNwmBusoffEnd( NM_CHANNEL_APPLTYPE_ONLY );


#endif /* __CAN_PAR_H__ */
